### ISSUE TITLE
For contributors: still see four (4) test failures under linux

### ISSUE THREAD

**Issue by kaiyuan01** [wenyan-lang/wenyan#441]
So I start everything anew from gitpod using the following image:

gitpod /workspace/wenyan-lang $ uname -a
Linux ws-6ad14f07-8523-4078-9ced-11a12b27494f 4.14.145+ #1 SMP Tue Oct 8 03:03:11 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

I ran the following from the console:
   
   22  npm run build
   23  npm test

**Tests failed with the following issues:**

 82 passing (6s)
  4 failing

  1) examples
       javascript
         divination:
     TypeError: Cannot use 'in' operator to search for '易經' in undefined
      at Object.compile (dist/core/index.min.js:1:10879)
      at runExample (test/examples.test.js:28:25)
      at Context.it (test/examples.test.js:57:24)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)

  2) examples
       javascript
         import:
     TypeError: Cannot use 'in' operator to search for '算經' in undefined
      at Object.compile (dist/core/index.min.js:1:10879)
      at runExample (test/examples.test.js:28:25)
      at Context.it (test/examples.test.js:57:24)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)

  3) examples
       romanizeIdentifiers
         divination:
     TypeError: Cannot use 'in' operator to search for '易經' in undefined
      at Object.compile (dist/core/index.min.js:1:10879)
      at runExample (test/examples.test.js:28:25)
      at Context.it (test/examples.test.js:57:24)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)

  4) examples
       romanizeIdentifiers
         import:
     TypeError: Cannot use 'in' operator to search for '算經' in undefined
      at Object.compile (dist/core/index.min.js:1:10879)
      at runExample (test/examples.test.js:28:25)
      at Context.it (test/examples.test.js:57:24)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)

npm ERR! Test failed.  See above for more details.
gitpod /workspace/wenyan-lang $

**Comment by kaiyuan01** [comment]
BTW, this can be reproduced using https://gitpod.io/#https://github.com/LingDong-/wenyan-lang and its console

**Comment by kaiyuan01** [comment]
I did a clean build and test it again, no issues any more. Could be from my local changes.

**Comment by cuixiping** [comment]
It's caused by some code in `parser.js`

```
    if (imports[i] in lib[lang]) {
      isrc = lib[lang][imports[i]];
    } else if (imports[i] in lib) {
      isrc = lib[imports[i]];
    } else {
      isrc = reader(imports[i]);
    }
```

`lib[lang]` can be undefined in some cases.

**Comment by antfu** [comment]
Did test out. Seems no issue for gitpod

![image](https://user-images.githubusercontent.com/11247099/71607021-00274200-2bb1-11ea-861d-ba0a511c6c47.png)

Commands I used.

```bash
npm i
npm run build
npm t
```
