### ISSUE TITLE
Example programs "draw_heart" and "helloworld" are not compiling into Ruby

### ISSUE THREAD

**Issue by Teashrock** [wenyan-lang/wenyan#584]
On "draw_heart" it just writes this:
```ruby
TypeError: Cannot read property '算經' of undefined
    at C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:1885:22
    at Array.map (<anonymous>)
    at Object.bundleImports (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:1884:20)
    at Object.extractMacros (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:4588:14)
    at Object.compile (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:812:26)
    at getCompiled (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:2251:21)
    at Object.<anonymous> (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:2200:24)
    at step (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:2124:23)
    at Object.next (C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:2105:53)
    at C:\Users\Teashrock\.vscode\extensions\antfu.wenyan-lang-0.11.4\dist\wenyan.js:2099:71

```

And this in "helloworld":
```ruby
SyntaxError: Unexpected character '#' (1:2)
> 1 | # encoding: UTF-8
    |  ^
  2 |   require 'forwardable'
  3 |     class Ctnr
  4 |       extend Forwardable
```

**Comment by antfu** [comment]
Our Ruby compiler is created by @Madao-3 and not actively maintained recently (wenyan have been evolved a lot since the last ruby compiler update). Sorry to tell you that none of our core team members are familiar with Ruby, so I think the Ruby support should be community driven for now. Contributions/PRs are greatly welcome. Thanks for understanding.

cc @LingDong-
